services:
  edge-mining-core:
    image: edge-mining-core:latest
    restart: unless-stopped
    build:
      context: .
    container_name: edge-mining-core
    environment:
      - TIMEZONE=Europe/Rome
      - SCHEDULER_INTERVAL_SECONDS=5
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
