services:
  edge-mining:
    image: edge-mining
    restart: unless-stopped
    build:
      context: .
    ports:
      - "80:80"
    environment:
      - TIMEZONE=Europe/Rome
      - SCHEDULER_INTERVAL_SECONDS=5
    volumes:
      - ./user_data/:/app/core/data

networks: {}
