"""Initial schema with all tables

Revision ID: 4e55fe6113c7
Revises:
Create Date: 2026-01-23 16:43:04.117164

"""

from typing import Sequence, Union

import sqlalchemy as sa

import edge_mining.adapters.domain.energy.tables
import edge_mining.adapters.domain.forecast.tables
import edge_mining.adapters.domain.home_load.tables
import edge_mining.adapters.domain.miner.tables
import edge_mining.adapters.domain.notification.tables
import edge_mining.adapters.domain.performance.tables
import edge_mining.adapters.domain.policy.tables

# Import custom types used in table definitions
import edge_mining.adapters.infrastructure.external_services.tables
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e55fe6113c7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_services",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("adapter_type", sa.String(), nullable=False),
        sa.Column(
            "config",
            edge_mining.adapters.infrastructure.external_services.tables.ExternalServiceConfigType(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_external_services_id"), "external_services", ["id"], unique=False)
    op.create_table(
        "home_profiles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("devices_json", edge_mining.adapters.domain.home_load.tables.LoadDevicesDictType(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "policies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("start_rules", edge_mining.adapters.domain.policy.tables.AutomationRulesListType(), nullable=True),
        sa.Column("stop_rules", edge_mining.adapters.domain.policy.tables.AutomationRulesListType(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_policies_id"), "policies", ["id"], unique=False)
    op.create_table(
        "settings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("settings_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "energy_monitors",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("adapter_type", sa.String(), nullable=False),
        sa.Column("config", edge_mining.adapters.domain.energy.tables.EnergyMonitorConfigType(), nullable=True),
        sa.Column("external_service_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["external_service_id"],
            ["external_services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_energy_monitors_id"), "energy_monitors", ["id"], unique=False)
    op.create_table(
        "forecast_providers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("adapter_type", sa.String(), nullable=False),
        sa.Column("config", edge_mining.adapters.domain.forecast.tables.ForecastProviderConfigType(), nullable=True),
        sa.Column("external_service_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["external_service_id"],
            ["external_services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_forecast_providers_id"), "forecast_providers", ["id"], unique=False)
    op.create_table(
        "home_forecast_providers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("adapter_type", sa.String(), nullable=False),
        sa.Column(
            "config", edge_mining.adapters.domain.home_load.tables.HomeForecastProviderConfigType(), nullable=True
        ),
        sa.Column("external_service_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["external_service_id"],
            ["external_services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_home_forecast_providers_id"), "home_forecast_providers", ["id"], unique=False)
    op.create_table(
        "miner_controllers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("adapter_type", sa.String(), nullable=False),
        sa.Column("config", edge_mining.adapters.domain.miner.tables.MinerControllerConfigType(), nullable=True),
        sa.Column("external_service_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["external_service_id"],
            ["external_services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_miner_controllers_id"), "miner_controllers", ["id"], unique=False)
    op.create_table(
        "mining_performance_trackers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("adapter_type", sa.String(), nullable=False),
        sa.Column(
            "config", edge_mining.adapters.domain.performance.tables.MiningPerformanceTrackerConfigType(), nullable=True
        ),
        sa.Column("external_service_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["external_service_id"],
            ["external_services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mining_performance_trackers_id"), "mining_performance_trackers", ["id"], unique=False)
    op.create_table(
        "notifiers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("adapter_type", sa.String(), nullable=False),
        sa.Column("config", edge_mining.adapters.domain.notification.tables.NotifierConfigType(), nullable=True),
        sa.Column("external_service_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["external_service_id"],
            ["external_services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifiers_id"), "notifiers", ["id"], unique=False)
    op.create_table(
        "energy_sources",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("nominal_power_max", sa.Float(), nullable=True),
        sa.Column("storage", sa.JSON(), nullable=True),
        sa.Column("grid", sa.JSON(), nullable=True),
        sa.Column("external_source", sa.Float(), nullable=True),
        sa.Column("energy_monitor_id", sa.String(), nullable=True),
        sa.Column("forecast_provider_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["energy_monitor_id"],
            ["energy_monitors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["forecast_provider_id"],
            ["forecast_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_energy_sources_id"), "energy_sources", ["id"], unique=False)
    op.create_table(
        "miners",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("status", edge_mining.adapters.domain.miner.tables.MinerStatusType(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("hash_rate", sa.String(), nullable=True),
        sa.Column("hash_rate_max", sa.String(), nullable=True),
        sa.Column("power_consumption", sa.Float(), nullable=True),
        sa.Column("power_consumption_max", sa.Float(), nullable=True),
        sa.Column("controller_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["controller_id"],
            ["miner_controllers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_miners_id"), "miners", ["id"], unique=False)
    op.create_table(
        "optimization_units",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("policy_id", sa.String(), nullable=True),
        sa.Column(
            "target_miner_ids", edge_mining.adapters.domain.optimization_unit.tables.EntityIdListType(), nullable=False
        ),
        sa.Column("energy_source_id", sa.String(), nullable=True),
        sa.Column("home_forecast_provider_id", sa.String(), nullable=True),
        sa.Column("performance_tracker_id", sa.String(), nullable=True),
        sa.Column(
            "notifier_ids", edge_mining.adapters.domain.optimization_unit.tables.EntityIdListType(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["energy_source_id"],
            ["energy_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_forecast_provider_id"],
            ["home_forecast_providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["performance_tracker_id"],
            ["mining_performance_trackers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_optimization_units_id"), "optimization_units", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_optimization_units_id"), table_name="optimization_units")
    op.drop_table("optimization_units")
    op.drop_index(op.f("ix_miners_id"), table_name="miners")
    op.drop_table("miners")
    op.drop_index(op.f("ix_energy_sources_id"), table_name="energy_sources")
    op.drop_table("energy_sources")
    op.drop_index(op.f("ix_notifiers_id"), table_name="notifiers")
    op.drop_table("notifiers")
    op.drop_index(op.f("ix_mining_performance_trackers_id"), table_name="mining_performance_trackers")
    op.drop_table("mining_performance_trackers")
    op.drop_index(op.f("ix_miner_controllers_id"), table_name="miner_controllers")
    op.drop_table("miner_controllers")
    op.drop_index(op.f("ix_home_forecast_providers_id"), table_name="home_forecast_providers")
    op.drop_table("home_forecast_providers")
    op.drop_index(op.f("ix_forecast_providers_id"), table_name="forecast_providers")
    op.drop_table("forecast_providers")
    op.drop_index(op.f("ix_energy_monitors_id"), table_name="energy_monitors")
    op.drop_table("energy_monitors")
    op.drop_table("settings")
    op.drop_index(op.f("ix_policies_id"), table_name="policies")
    op.drop_table("policies")
    op.drop_table("home_profiles")
    op.drop_index(op.f("ix_external_services_id"), table_name="external_services")
    op.drop_table("external_services")
    # ### end Alembic commands ###
